[da]
celestia_rpc_auth_token = "SUPER_SECRET_TOKEN"
celestia_rpc_address = "http://localhost:11111/"
# 100 MB
max_celestia_response_body_size = 104_857_600

[storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "demo_data"

[runner.storage]
path = "demo_data"

[runner]
start_height = 671431

[runner.rpc_config]
# the host and port to bind the rpc server for
bind_host = "127.0.0.1"
bind_port = 12345
