[da]
celestia_rpc_auth_token = ""
celestia_rpc_address = "http://127.0.0.1:26658"
max_celestia_response_body_size = 104_857_600
celestia_rpc_timeout_seconds = 60

[storage]
path = "demo_data"

[runner]
start_height = 1

[runner.rpc_config]
bind_host = "127.0.0.1"
bind_port = 12345
