[package]
name = "jupiter"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = { workspace = true, features = ["bytes"] }
bech32 = { workspace = true }
prost = "0.11"
prost-types = "0.11"
tendermint = "0.32"
tendermint-proto = "0.32"

# Convenience
anyhow = { workspace = true }
sha2 = { workspace = true }
base64 = "0.13.1"
hex = { version = "0.4.3", features = ["serde"] }
hex-literal = "0.3.4"
jsonrpsee = { version = "0.16.2", features = ["http-client"], optional = true }
reqwest = { version = "0.11.13", features = ["blocking"], optional = true }
serde = { workspace = true }
serde_cbor = "0.11.2"
serde_json = { workspace = true }
tokio = { workspace = true, optional = true }
thiserror = { workspace = true }
tracing = "0.1.37"

sov-rollup-interface = { path = "../../rollup-interface" }
nmt-rs = { git = "https://github.com/Sovereign-Labs/nmt-rs.git", rev = "dd37588444fca72825d11fe4a46838f66525c49f", features = ["serde", "borsh"] }

[dev-dependencies]
postcard = { version = "1", features = ["use-std"] }
proptest = { version = "1.2" }
wiremock = "0.5"

[build-dependencies]
prost-build = { version = "0.11" }


[features]
default = ["native"]
native = ["dep:tokio", "dep:reqwest", "dep:jsonrpsee"]
verifier = []
