[package]
name = "sov-blob-storage"
description = "A Sovereign SDK module for holding blobs from Data Availability Layer"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"

resolver = "2"


[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }

sov-rollup-interface = { path = "../../../rollup-interface", version = "0.1" }
sov-modules-api = { path = "../../sov-modules-api", version = "0.1" }
sov-modules-macros = { path = "../../sov-modules-macros", version = "0.1" }
sov-state = { path = "../../sov-state", version = "0.1" }
sov-sequencer-registry = { path = "../sov-sequencer-registry", version = "0.1" }


schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
jsonrpsee = { workspace = true, optional = true }
clap = { workspace = true, optional = true }

[dev-dependencies]
sov-rollup-interface = { path = "../../../rollup-interface", features = ["mocks"] }
sov-bank = { path = "../sov-bank", version = "0.1" }
tempfile = { workspace = true }

[features]
default = []
native = [
    "jsonrpsee",
    "schemars",
    "serde",
    "serde_json",
    "sov-modules-api/native",
    "sov-state/native",
    "sov-modules-macros/native",
    "sov-sequencer-registry/native"
]
