[package]
name = "demo-nft-module"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = "sovereign.xyz"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
serde = { workspace = true, optional = true }

sov-modules-api = { path = "../../module-system/sov-modules-api", default-features = false, features = ["macros"] }
sov-state = { path = "../../module-system/sov-state", default-features = false }

[dev-dependencies]
sov-rollup-interface = { path = "../../rollup-interface" }
tempfile = { workspace = true }


[features]
default = ["native"]
serde = ["dep:serde"]
native = ["serde", "sov-state/native", "sov-modules-api/native"]
