start_height = 671431
[da]
celestia_rpc_auth_token = "SUPER_SECRET_TOKEN"
celestia_rpc_address = "http://localhost:11111/"
# 100 MB
max_celestia_response_body_size = 104_857_600
[runner.storage]
path = "demo_data"
