[package]
name = "sov-demo-rollup"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = "sovereign.xyz"
publish = false
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }
borsh = { workspace = true, features = ["bytes"] }
jsonrpsee = { workspace = true, features = ["http-client", "server"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }
bytes = { workspace = true }
futures = "0.3"

# Crates which only this package depends on 
tokio = { workspace = true }
tracing-subscriber = "0.3.17"

jupiter = { path = "../../adapters/celestia" }
demo-stf = { path = "../demo-stf", features = ["native"] }
sov-rollup-interface = { path = "../../rollup-interface" }
sov-db = { path = "../../full-node/db/sov-db" }
sov-ethereum = { path = "../../full-node/sov-ethereum", optional = true }
sov-sequencer = { path = "../../full-node/sov-sequencer" }
risc0-adapter = { path = "../../adapters/risc0" }
sov-modules-stf-template = { path = "../../module-system/sov-modules-stf-template" }

sov-bank = { path = "../../module-system/module-implementations/sov-bank", default-features = false }
sov-election = { path = "../../module-system/module-implementations/examples/sov-election", default-features = false }
sov-value-setter = { path = "../../module-system/module-implementations/examples/sov-value-setter", default-features = false }
sov-modules-api = { path = "../../module-system/sov-modules-api", features = ["native"] }
sov-state = { path = "../../module-system/sov-state", features = ["native"] }
const-rollup-config = { path = "../const-rollup-config" }

[dev-dependencies]
sha2 = { workspace = true }
reqwest = "0.11"
tendermint = "0.32"
tempfile = { workspace = true }
proptest = { workspace = true }
clap = { workspace = true }
sov-rollup-interface = { path = "../../rollup-interface", features = ["fuzzing"] }
prometheus = "0.11.0"
prettytable-rs = "^0.10"
criterion = "0.5.1"

[features]
experimental = ["sov-ethereum/experimental"]

[[bench]]
name = "rollup_bench"
harness = false

[[bench]]
name = "rollup_coarse_measure"
harness = false
